### ISSUE TITLE
complete intron annotation

### ISSUE THREAD

**Issue by ahorvath** [Jill-Moore/SPombe-Splicing#1]
Dear Developers,

Many thanks for the great work! This is a significant achievement for the pombe community.
Do you happen to have an aggregated final intron list with all the features including the corrected and the newly annotated ones?

Many thanks.  

Bests,
Attila

**Comment by Jill-Moore** [comment]
Hello Attila:

We do not have a master file intron list but you can simply aggregate our annotations with those from PomBase. All our annotations are in reference to ASM294V2.26. The new and previously misannotated introns can be found in Table S2. Our branch point predictions can be found in Table S4.

Please let me know if you have additional questions.

Many thanks,
Jill

**Comment by ahorvath** [comment]
Thanks for your prompt answer. I checked out your code and it works for ASM294v2.35.gtf. This gives pretty similar results (5,364 introns).  It doesn't work for [ASM294v2.26](ftp://ftp.ensemblgenomes.org/pub/release-26/fungi/gtf/schizosaccharomyces_pombe) though. I guess this is because of the slightly different gtf format.
Using a slightly modified Create-Annotation-Files.sh version: 

awk '{if ($3== "exon") print $1 "\t" $4 "\t" $5 "\t" **$14** "\t" "." "\t" $7 "\t" \
     $10}' $gtf | awk '{gsub(/;/," ");print}' | awk '{gsub(/"/,"");print}' \
     > Exons.bed
 
That gives 5,360 introns. Was your original number 5,303? 

Many thanks,
Attila

**Comment by ahorvath** [comment]
With a reasonable length threshold for the introns (>20), I got the same number. 

Many thanks and we will cite the paper accordingly.
